### ISSUE TITLE
请问index.sense 和index.sense.gloss是从wordnet哪里得到的？

### ISSUE THREAD

**Issue by Haitons** [HSLCY/GlossBERT#1]
您好，我看了Wordnet的网站，并没有找到这两个文件，请问这两个文件是从哪里得到的？可以说一下每一列的意义是什么吗？

**Comment by HSLCY** [comment]
你好，[WordNet网站的这里](http://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz)可以下载WordNet 3.0，里面的`WordNet-3.0/dict/index.sense`就是我们使用的`index.sense`（你可以理解成WordNet所有的词都在这里了），`index.sense.gloss`是我们把dict目录下其他的文件中的gloss索引出来了整合了进来加到了最后一列方便后面做实验用的。

`index.sense.gloss`一共5列，分别代表：sense_key, synset_offset, sense_number, tag_cnt, gloss
详细的内容建议阅读WordNet的文档哦，[这一页](https://wordnet.princeton.edu/documentation/senseidx5wn)是关于`index.sense`的。

**Comment by Haitons** [comment]
明白了，谢谢！
